### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chenchunyii**
http://13.112.252.173:3000/

我是群嶧 ~

### CODE REVIEW

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/


我是群嶧 ~

**Review by cwpeng — APPROVED** [review]
I try to book twice and your get booking API goes 500 error.

**Comment by cwpeng** [comment]
Sorry for accidentally approving. There is issue waiting your fix.

**Comment by chenchunyii** [comment]
不要嚇偶～我有點快發燒@@

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/

※修正check booking邏輯

我是群嶧 ~

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/

※修正check booking邏輯

我是群嶧 ~

**Pull request merged**
