### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chenchunyii**
http://13.112.252.173:3000/

我是群嶧~

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Mobile layout is broken.
2. Hide category block after we click one of them.
13 112 252 173_3000_(Samsung Galaxy S8+)

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/

1/點擊category即消失處裡
2/爆版處理

我是群嶧~

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/

1/點擊category即消失處裡
2/爆版處理

我是群嶧~

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
