### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by chenchunyii**
http://13.112.252.173:3000/api/attractions?page=1
http://13.112.252.173:3000/api/attractions?page=0&keyword=藝文館所
http://13.112.252.173:3000/api/attractions?page=0&keyword=北
http://13.112.252.173:3000/api/attraction/10

看到網頁畫面出來的時候好開心 ~~
我是群嶧

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. http://13.112.252.173:3000/api/attractions?page=2&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80 does not filter data by keyword.
2. "images" field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"

Solve issues and re-request review.

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/api/attractions?page=1
[http://13.112.252.173:3000/api/attractions?page=0&keyword=藝文館所](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://13.112.252.173:3000/api/attractions?page=0&keyword=北](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://13.112.252.173:3000/api/attraction/10

我是群嶧

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Every attraction should contain 1 or more images, but yours always contain only 1 image.
2. Use second parameter of execute method to combine variable into SQL query.

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/api/attractions?page=1
[http://13.112.252.173:3000/api/attractions?page=0&keyword=藝文館所](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://13.112.252.173:3000/api/attractions?page=0&keyword=北](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://13.112.252.173:3000/api/attraction/10


網址切割OK ~

我是群嶧

**Review by cwpeng — CHANGES_REQUESTED** [review]
1 is solved.

But we should always second parameter of execute method to combine variable into SQL query for SQL Injection Prevestion as we discussed weeks ago.

**Comment by chenchunyii** [comment]
http://13.112.252.173:3000/api/attractions?page=1
[http://13.112.252.173:3000/api/attractions?page=0&keyword=藝文館所](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E8%97%9D%E6%96%87%E9%A4%A8%E6%89%80)
[http://13.112.252.173:3000/api/attractions?page=0&keyword=北](http://13.112.252.173:3000/api/attractions?page=0&keyword=%E5%8C%97)
http://13.112.252.173:3000/api/attraction/10

修改execute用法

我是群嶧

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
